name: Release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  REGISTRY: ${{ secrets.ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Authenticate Docker to Registry
      id: authenticate-docker 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REGISTRY 
    - name: Build, Tag, and Push Image to AWS ECR
      id: build-image
      env:
        IMAGE_REPO: ${{ github.event.repository.name }}
        IMAGE_TAG: ${{ github.ref }} #github.sha }}
        TAGGED_IMAGE: $REGISTRY/$IMAGE_REPO:$IMAGE_TAG
      run: |
        docker build -t $TAGGED_IMAGE .
        docker push $TAGGED_IMAGE
    - name: Publish Release
      id: publish-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false 
        prerelease: false